model:
  type: base_ae_v2
  model_name: base_ae_v2
  model_kwargs:

data_path: ./test

seed: 42
model_dir: ./artifacts/base_ae_v2-b_2-lr_3e04-b_s_2/epoch_799
batch_size: 64
output_filename: ./artifacts/base_ae_v2-b_2-lr_3e04-b_s_2/epoch_799/base_ae-b_2-lr_3e04.png
b: 2