model:
  type: custom_regularization
  model_name: custom_regularization
  model_kwargs:

data:
  train_data_path: ./train
  test_data_path: ./test

training_args:
  seed: 42
  use_cuda: True
  batch_size: 64
  epochs: 1000
  learning_rate: 3.0e-03
  eval_epochs: 200
  output_dir: ./artifacts
  run_name: custom_regularization-b_2-1000_epochs-lr_3e04
  b_t: 2